[versions]
kotlin-plugin = "2.0.0"
apollo = "4.0.0-beta.7"
kotlinx-coroutines = "1.8.0"
okio = "3.9.0"
atomicfu = "0.24.0"

[libraries]
librarian = "com.gradleup.librarian:core:0.0.2"
kgp = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }
apollo-api = { group = "com.apollographql.apollo3", name = "apollo-api", version.ref = "apollo" }
apollo-mpp-utils = { group = "com.apollographql.apollo3", name = "apollo-mpp-utils", version.ref = "apollo" }
apollo-testing-support = { group = "com.apollographql.apollo3", name = "apollo-testing-support", version.ref = "apollo" }
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime", version.ref = "apollo" }
atomicfu-library = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "atomicfu" }
atomicfu-plugin = { group = "org.jetbrains.kotlinx", name = "atomicfu-gradle-plugin", version.ref = "atomicfu" }
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1"
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" } # the Kotlin plugin resolves the version
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
uuid = "com.benasher44:uuid:0.8.2"
